version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: highlevel_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: highlevel
      MYSQL_USER: highlevel
      MYSQL_PASSWORD: highlevel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
